//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISAM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i474337
        ///i340243
        ///i617989
        ///i716491
        ///i371112
        ///i590058
        ///i432874
        ///i876058
        ///i460329
        ///i483133
        ///i147357
        ///i555822
        ///i519986
        ///i62670
        ///i12258
        ///i919749
        ///i283424
        ///i162648
        ///i839082
        ///i265317
        ///i127238
        ///i536242
        ///i540079
        ///i453597
        ///i538106
        ///i512291
        ///i524887
        ///i427236
        ///i955422
        ///i681746
        ///i224995
        ///i844034
        ///i505552
        ///i794317
        ///i270777
        ///i96890
        ///i735501
        ///i49665
        ///i894079
        ///i534322
        ///i428205
        ///i801546
        ///i417585
        ///i184188
        ///i898364
        ///i730539
        ///i204736
        ///i419712
        ///i735454
        ///i614326
        ///i176085
        ///i558327
        ///i931575
        ///i503748
        ///i820143
        ///i370474
        ///i712084
        ///i18 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomData10000 {
            get {
                return ResourceManager.GetString("RandomData10000", resourceCulture);
            }
        }
    }
}
